### ISSUE TITLE
cyclicHeatTransferPimpleFoam about 3D channel flow

### ISSUE THREAD

**Issue by OYYO1999** [michaelcoe/cyclicHeatTransfer-OpenFOAM#1]
hello, i have a problem about 3D channel flow solved by cyclicHeatTransferPimpleFoam. The boundary conditions are similar with the file (case-files), but the errors as:
![Screenshot from 2024-08-17 14-31-09](https://github.com/user-attachments/assets/fc071326-6151-470c-ac0d-5de63b25be3f)
i don't know why, can you give some advice?

**Comment by michaelcoe** [comment]
This is a bit hard to diagnose without knowing more.  Have you checked your mesh? What version of Openfoam are you running?  Where there any errors with compiling?  Was this during the calculation of the thermal decay rate?  Please provide me more information.

**Comment by OYYO1999** [comment]
oh!! thanks for your reply. my mesh is OK, and has solved with other solvers like PimpleFoam. the version of Openfoam is v2206. no errors in compiling cyclicHeatTransferPimpleFoam, some warning appeared like:
![Screenshot from 2024-08-17 14-51-12](https://github.com/user-attachments/assets/43d52074-dae6-4f85-8859-a1e7962281d4)
this should be the time to calculate thetaBar? 
Here is some  information:
turbulence model  is  laminar
so ./0 file include p, T, thetaBar, and U.
the domain is:
![Screenshot from 2024-08-17 15-03-00](https://github.com/user-attachments/assets/e19e4999-5963-4727-8f09-d8d56a8433da)
this is T boundary file details
![Screenshot from 2024-08-17 15-00-42](https://github.com/user-attachments/assets/aff6a42f-2706-48bb-a4d7-e9ef67532975)
the fvSolution and fvschemes are same as the cyclicHeatTransferPimpleFoam  solver.
this is initialConditions
![Screenshot from 2024-08-17 15-05-35](https://github.com/user-attachments/assets/d2bafbcb-91dc-4212-80aa-347396c123d7)

**Comment by michaelcoe** [comment]
I think the problem is your walls.  To calculate thetabar, you need to have a flux of heat through the wall boundaries, but you don't have a patch that's a wall.  The solver looks for two patches in the lambdaEqn.h file:

`label inletID = mesh.boundaryMesh().findPatchID("inlet");
label wallsID = mesh.boundaryMesh().findPatchID("walls");`

The mathematics behind the solver require a wall and an inlet to calculate the thermal decay rate (lambda).  I think if you rename SLIP to walls, then it you might not get the error anymore. Or you can change the above line in lambdaEqn.h to find which patch your actual wall is.  There might be a way to find all walls, and I can look into that, but essentially your wall patches need to be called "walls" in the current implementation.

**Comment by OYYO1999** [comment]
I understand a little, this means my walls all are not consider as wall boundary. it is very frustrating.
thus, how to change the above line in lambdaEqn.h, i am confusing. like：
`label wallsID = mesh.boundaryMesh().findPatchID("WALL-BOTTOM");`?
Does the SLIP boundary as `slip` condition influence the computation?

**Comment by michaelcoe** [comment]
an easier solution would just be to name your wall boundary patch "walls,"  but this would also do the trick.  Note that that would only calculate the wall flux on the "WALL-BOTTOM" boundary and not any other walls you have. Multiple walls would need to be grouped under the boundary "walls" as I've done in the blockMeshDict of the validation case.  Also, the walls would need to have the same initial temperature.  My paper also goes over some of the limitations of the solver:  https://doi.org/10.51560/ofj.v3.113

**Comment by OYYO1999** [comment]
OK, i am fine. The solution is to change constant/polyMesh/boundary file, changing "WALL-BOTTOM"  to "walls" boundary. the 0/p,U,T,thetaBar file also were changed.
Thanks for your answer!
