### ISSUE TITLE
What are the definitions of thermalGamma and lamdaInterval in 0/include/initialConditions？

### ISSUE THREAD

**Issue by OYYO1999** [michaelcoe/cyclicHeatTransfer-OpenFOAM#2]
`thermalGamma        0.001;`
`lambdaInterval      20;`
Hi
thermalGamma and lamdaInterval in 0/include/initialConditions confuse me。
I read your paper [https://doi.org/10.51560/ofj.v3.113](url), but did not find the relevant definition.
Can you provide some information?

**Comment by michaelcoe** [comment]
`thermalGamma` is a variable that I was using when I was trying to adapt this method for entropy and internal energy in order to bring the method inline with the buoyantPimpleFoam method of calculating the temperature field variables using Enthalpy.

`lambdaInterval` is the amount of iterations / time steps in between recalculating the thermal decay rate (lambda_L).  This is needed to settle the temperature field variables in between calculations.

**Comment by OYYO1999** [comment]
How should I define `thermalGamma` value？

**Comment by michaelcoe** [comment]
Just comment it out or delete it.  It's not used anywhere in the solver. If you want to see what is read by the solver, you can see everything in the readTransportProperties.h file.

**Comment by OYYO1999** [comment]
Ok, thank you very much for your answer.
