### ISSUE TITLE
How to gauss and assign a value to lambdaGuess?

### ISSUE THREAD

**Issue by OYYO1999** [michaelcoe/cyclicHeatTransfer-OpenFOAM#3]
Hi
Sorry to bother you again.

The choice of value for `lambdaGuess` confuses me，i dont konw how to gauss, like Figure 5 in your paper??

By the way, i am confused by the temperature profile in Figure 6 of your paper., why is the temperature near the wall 0?

**Comment by michaelcoe** [comment]
`lambdaGuess` is just a guess of what it would be.  It is there because during the initial stages, you don't know what `lambda` is until it's calculated after the delay. 

The temperature field is normalized to be a parabola such that the walls are 0 and the middle is 1.  We assume this as the shape of the temperature field for fully developed, periodic flow. Note that Theta and Thetabar are actually normalized values. 

You can read the paper I based my research on: Wang et al. 2017  https://doi.org/10.1103/PhysRevE.95.063309 and Harikrishnan and Tiwari 2020 https://doi.org/10.1007/978-981-15-0124-1_78. Also, the original periodic / cyclic heat transfer paper by Patankar et al. 1977 https://doi.org/10.1016/j.ijheatmasstransfer.2012.01.010.

**Comment by OYYO1999** [comment]
Got it. I have an another question，T should not be cyclic. What is the role of T in the 0/ folder? It should not be involved in the calculation.

**Comment by michaelcoe** [comment]
You are essentially back calculating T from Theta and Thetabar, so you need the field variable to be initialized.  Also, you are specifying a constant wall temperature which happens in the T file.  The really important part is to make sure that the domain length matches with your domain length in the flow direction.

**Comment by OYYO1999** [comment]
I understand, i read the solver-files/heatTransfer/cyclicHeatPimpleFoam file, the TEqn.H file does not include. But how will the T field be calculated afterwards? What commands do not need to be executed?

**Comment by michaelcoe** [comment]
If you look in thetaEqn.h, you'll see where theta is calculated, and from that, we can get temperature in the next line.

**Comment by OYYO1999** [comment]
OK, i understand. Recently I read some papers about this cyclicHeatTransfer problem. Some jobs are different from your approach, 
like this https://doi.org/10.1016/j.ijheatfluidflow.2009.02.023
![2024-08-24 084816](https://github.com/user-attachments/assets/686e8389-db36-40eb-b03b-74edc10c1a9a)
What is the difference? Intuitively, it feels more direct.

**Comment by michaelcoe** [comment]
It looks like that paper references constant heat flux through the walls, which is more straightforward than constant wall temperature. In the original work by Patankar, he divides the two cases up because constant wall temperature is a much harder problem than constant wall heat flux. There are a few examples of OpenFOAM code for constant heat flux: https://zenodo.org/records/1254574.

**Comment by OYYO1999** [comment]
Thank you very much for your answer. I will study it carefully.
